// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: protodefine/router/router.proto

package router

import (
	proto "github.com/golang/protobuf/proto"
	mytype "go_game/protodefine/mytype"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CMDID_Router int32

const (
	CMDID_Router_IDUnknow         CMDID_Router = 0 //0保留
	CMDID_Router_IDTransferData   CMDID_Router = 1 //router的转发数据包
	CMDID_Router_IDRegisterAppReq CMDID_Router = 2 //其他APP向router发送的注册请求
	CMDID_Router_IDRegisterAppRsp CMDID_Router = 3 //router的注册回复
	CMDID_Router_IDLast           CMDID_Router = 100
)

// Enum value maps for CMDID_Router.
var (
	CMDID_Router_name = map[int32]string{
		0:   "IDUnknow",
		1:   "IDTransferData",
		2:   "IDRegisterAppReq",
		3:   "IDRegisterAppRsp",
		100: "IDLast",
	}
	CMDID_Router_value = map[string]int32{
		"IDUnknow":         0,
		"IDTransferData":   1,
		"IDRegisterAppReq": 2,
		"IDRegisterAppRsp": 3,
		"IDLast":           100,
	}
)

func (x CMDID_Router) Enum() *CMDID_Router {
	p := new(CMDID_Router)
	*p = x
	return p
}

func (x CMDID_Router) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMDID_Router) Descriptor() protoreflect.EnumDescriptor {
	return file_protodefine_router_router_proto_enumTypes[0].Descriptor()
}

func (CMDID_Router) Type() protoreflect.EnumType {
	return &file_protodefine_router_router_proto_enumTypes[0]
}

func (x CMDID_Router) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMDID_Router.Descriptor instead.
func (CMDID_Router) EnumDescriptor() ([]byte, []int) {
	return file_protodefine_router_router_proto_rawDescGZIP(), []int{0}
}

type RouterTransferData_DataDirection int32

const (
	RouterTransferData_App2App    RouterTransferData_DataDirection = 0
	RouterTransferData_App2Client RouterTransferData_DataDirection = 1
	RouterTransferData_Client2App RouterTransferData_DataDirection = 2
)

// Enum value maps for RouterTransferData_DataDirection.
var (
	RouterTransferData_DataDirection_name = map[int32]string{
		0: "App2App",
		1: "App2Client",
		2: "Client2App",
	}
	RouterTransferData_DataDirection_value = map[string]int32{
		"App2App":    0,
		"App2Client": 1,
		"Client2App": 2,
	}
)

func (x RouterTransferData_DataDirection) Enum() *RouterTransferData_DataDirection {
	p := new(RouterTransferData_DataDirection)
	*p = x
	return p
}

func (x RouterTransferData_DataDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouterTransferData_DataDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_protodefine_router_router_proto_enumTypes[1].Descriptor()
}

func (RouterTransferData_DataDirection) Type() protoreflect.EnumType {
	return &file_protodefine_router_router_proto_enumTypes[1]
}

func (x RouterTransferData_DataDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouterTransferData_DataDirection.Descriptor instead.
func (RouterTransferData_DataDirection) EnumDescriptor() ([]byte, []int) {
	return file_protodefine_router_router_proto_rawDescGZIP(), []int{0, 0}
}

type RouterTransferData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base                *mytype.BaseInfo                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DestApptype         uint32                           `protobuf:"varint,2,opt,name=dest_apptype,json=destApptype,proto3" json:"dest_apptype,omitempty"`
	DestAppid           uint32                           `protobuf:"varint,3,opt,name=dest_appid,json=destAppid,proto3" json:"dest_appid,omitempty"`
	SrcApptype          uint32                           `protobuf:"varint,4,opt,name=src_apptype,json=srcApptype,proto3" json:"src_apptype,omitempty"`
	SrcAppid            uint32                           `protobuf:"varint,5,opt,name=src_appid,json=srcAppid,proto3" json:"src_appid,omitempty"`
	DataCmdKind         uint32                           `protobuf:"varint,6,opt,name=data_cmd_kind,json=dataCmdKind,proto3" json:"data_cmd_kind,omitempty"`
	DataCmdSubid        uint32                           `protobuf:"varint,7,opt,name=data_cmd_subid,json=dataCmdSubid,proto3" json:"data_cmd_subid,omitempty"`
	Data                []byte                           `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	DataDirection       RouterTransferData_DataDirection `protobuf:"varint,9,opt,name=data_direction,json=dataDirection,proto3,enum=bs.router.RouterTransferData_DataDirection" json:"data_direction,omitempty"`
	ClientRemoteAddress string                           `protobuf:"bytes,10,opt,name=client_remote_address,json=clientRemoteAddress,proto3" json:"client_remote_address,omitempty"`
	AttGateid           uint32                           `protobuf:"varint,11,opt,name=att_gateid,json=attGateid,proto3" json:"att_gateid,omitempty"`
	AttUserid           uint64                           `protobuf:"varint,12,opt,name=att_userid,json=attUserid,proto3" json:"att_userid,omitempty"`
	AttGateconnid       uint64                           `protobuf:"varint,13,opt,name=att_gateconnid,json=attGateconnid,proto3" json:"att_gateconnid,omitempty"`
}

func (x *RouterTransferData) Reset() {
	*x = RouterTransferData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodefine_router_router_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouterTransferData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterTransferData) ProtoMessage() {}

func (x *RouterTransferData) ProtoReflect() protoreflect.Message {
	mi := &file_protodefine_router_router_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterTransferData.ProtoReflect.Descriptor instead.
func (*RouterTransferData) Descriptor() ([]byte, []int) {
	return file_protodefine_router_router_proto_rawDescGZIP(), []int{0}
}

func (x *RouterTransferData) GetBase() *mytype.BaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RouterTransferData) GetDestApptype() uint32 {
	if x != nil {
		return x.DestApptype
	}
	return 0
}

func (x *RouterTransferData) GetDestAppid() uint32 {
	if x != nil {
		return x.DestAppid
	}
	return 0
}

func (x *RouterTransferData) GetSrcApptype() uint32 {
	if x != nil {
		return x.SrcApptype
	}
	return 0
}

func (x *RouterTransferData) GetSrcAppid() uint32 {
	if x != nil {
		return x.SrcAppid
	}
	return 0
}

func (x *RouterTransferData) GetDataCmdKind() uint32 {
	if x != nil {
		return x.DataCmdKind
	}
	return 0
}

func (x *RouterTransferData) GetDataCmdSubid() uint32 {
	if x != nil {
		return x.DataCmdSubid
	}
	return 0
}

func (x *RouterTransferData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RouterTransferData) GetDataDirection() RouterTransferData_DataDirection {
	if x != nil {
		return x.DataDirection
	}
	return RouterTransferData_App2App
}

func (x *RouterTransferData) GetClientRemoteAddress() string {
	if x != nil {
		return x.ClientRemoteAddress
	}
	return ""
}

func (x *RouterTransferData) GetAttGateid() uint32 {
	if x != nil {
		return x.AttGateid
	}
	return 0
}

func (x *RouterTransferData) GetAttUserid() uint64 {
	if x != nil {
		return x.AttUserid
	}
	return 0
}

func (x *RouterTransferData) GetAttGateconnid() uint64 {
	if x != nil {
		return x.AttGateconnid
	}
	return 0
}

type RegisterAppReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base      *mytype.BaseInfo `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	AuthKey   string           `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	AttData   string           `protobuf:"bytes,3,opt,name=att_data,json=attData,proto3" json:"att_data,omitempty"`
	MyAddress string           `protobuf:"bytes,4,opt,name=my_address,json=myAddress,proto3" json:"my_address,omitempty"`
	AppType   uint32           `protobuf:"varint,5,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	AppId     uint32           `protobuf:"varint,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *RegisterAppReq) Reset() {
	*x = RegisterAppReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodefine_router_router_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppReq) ProtoMessage() {}

func (x *RegisterAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_protodefine_router_router_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppReq.ProtoReflect.Descriptor instead.
func (*RegisterAppReq) Descriptor() ([]byte, []int) {
	return file_protodefine_router_router_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAppReq) GetBase() *mytype.BaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RegisterAppReq) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *RegisterAppReq) GetAttData() string {
	if x != nil {
		return x.AttData
	}
	return ""
}

func (x *RegisterAppReq) GetMyAddress() string {
	if x != nil {
		return x.MyAddress
	}
	return ""
}

func (x *RegisterAppReq) GetAppType() uint32 {
	if x != nil {
		return x.AppType
	}
	return 0
}

func (x *RegisterAppReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type RegisterAppRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base      *mytype.BaseInfo `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	RegResult uint32           `protobuf:"varint,2,opt,name=reg_result,json=regResult,proto3" json:"reg_result,omitempty"`
}

func (x *RegisterAppRsp) Reset() {
	*x = RegisterAppRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodefine_router_router_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAppRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppRsp) ProtoMessage() {}

func (x *RegisterAppRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protodefine_router_router_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppRsp.ProtoReflect.Descriptor instead.
func (*RegisterAppRsp) Descriptor() ([]byte, []int) {
	return file_protodefine_router_router_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAppRsp) GetBase() *mytype.BaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RegisterAppRsp) GetRegResult() uint32 {
	if x != nil {
		return x.RegResult
	}
	return 0
}

var File_protodefine_router_router_proto protoreflect.FileDescriptor

var file_protodefine_router_router_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2f, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x62, 0x73, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x1a, 0x1e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2f, 0x6d, 0x79, 0x74, 0x79, 0x70, 0x65,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x04, 0x0a,
	0x12, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x62, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64,
	0x65, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x41, 0x70, 0x70, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x64, 0x65, 0x73, 0x74, 0x41, 0x70, 0x70, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x72, 0x63, 0x5f, 0x61, 0x70, 0x70, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x73, 0x72, 0x63, 0x41, 0x70, 0x70, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x72, 0x63, 0x5f, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x73, 0x72, 0x63, 0x41, 0x70, 0x70, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x63, 0x6d, 0x64, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6d, 0x64, 0x4b, 0x69, 0x6e, 0x64, 0x12,
	0x24, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6d, 0x64, 0x5f, 0x73, 0x75, 0x62, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6d, 0x64,
	0x53, 0x75, 0x62, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x52, 0x0a, 0x0e, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2b, 0x2e, 0x62, 0x73, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d,
	0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a,
	0x15, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x69, 0x64, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x74, 0x74, 0x47, 0x61, 0x74, 0x65, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x74, 0x74, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x69,
	0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x47, 0x61, 0x74, 0x65,
	0x63, 0x6f, 0x6e, 0x6e, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x32, 0x41,
	0x70, 0x70, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x32, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x32, 0x41,
	0x70, 0x70, 0x10, 0x02, 0x22, 0xbf, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x74,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x74,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x79, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x41, 0x70, 0x70, 0x52, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a,
	0x68, 0x0a, 0x0c, 0x43, 0x4d, 0x44, 0x49, 0x44, 0x5f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12,
	0x0c, 0x0a, 0x08, 0x49, 0x44, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x49, 0x44, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x10,
	0x01, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x44, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x44, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x70, 0x70, 0x52, 0x73, 0x70, 0x10, 0x03, 0x12, 0x0a, 0x0a,
	0x06, 0x49, 0x44, 0x4c, 0x61, 0x73, 0x74, 0x10, 0x64, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x6f, 0x5f,
	0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protodefine_router_router_proto_rawDescOnce sync.Once
	file_protodefine_router_router_proto_rawDescData = file_protodefine_router_router_proto_rawDesc
)

func file_protodefine_router_router_proto_rawDescGZIP() []byte {
	file_protodefine_router_router_proto_rawDescOnce.Do(func() {
		file_protodefine_router_router_proto_rawDescData = protoimpl.X.CompressGZIP(file_protodefine_router_router_proto_rawDescData)
	})
	return file_protodefine_router_router_proto_rawDescData
}

var file_protodefine_router_router_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protodefine_router_router_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protodefine_router_router_proto_goTypes = []interface{}{
	(CMDID_Router)(0),                     // 0: bs.router.CMDID_Router
	(RouterTransferData_DataDirection)(0), // 1: bs.router.RouterTransferData.DataDirection
	(*RouterTransferData)(nil),            // 2: bs.router.RouterTransferData
	(*RegisterAppReq)(nil),                // 3: bs.router.RegisterAppReq
	(*RegisterAppRsp)(nil),                // 4: bs.router.RegisterAppRsp
	(*mytype.BaseInfo)(nil),               // 5: bs.types.BaseInfo
}
var file_protodefine_router_router_proto_depIdxs = []int32{
	5, // 0: bs.router.RouterTransferData.base:type_name -> bs.types.BaseInfo
	1, // 1: bs.router.RouterTransferData.data_direction:type_name -> bs.router.RouterTransferData.DataDirection
	5, // 2: bs.router.RegisterAppReq.base:type_name -> bs.types.BaseInfo
	5, // 3: bs.router.RegisterAppRsp.base:type_name -> bs.types.BaseInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protodefine_router_router_proto_init() }
func file_protodefine_router_router_proto_init() {
	if File_protodefine_router_router_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protodefine_router_router_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouterTransferData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodefine_router_router_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterAppReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodefine_router_router_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterAppRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protodefine_router_router_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protodefine_router_router_proto_goTypes,
		DependencyIndexes: file_protodefine_router_router_proto_depIdxs,
		EnumInfos:         file_protodefine_router_router_proto_enumTypes,
		MessageInfos:      file_protodefine_router_router_proto_msgTypes,
	}.Build()
	File_protodefine_router_router_proto = out.File
	file_protodefine_router_router_proto_rawDesc = nil
	file_protodefine_router_router_proto_goTypes = nil
	file_protodefine_router_router_proto_depIdxs = nil
}
